# example netlify.toml
[build]
    command = "yarn run build" # this is a higher priority command, instead of gui online
    # functions = "functions"
    publish = "dist"

## more info https://www.netlify.com/docs/netlify-toml-reference